spring:
  application:
    name: GCVD2025

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 5
          max-idle: 3
          min-idle: 1
          max-wait: 3000ms

springdoc:
  swagger-ui:
    path: ${SWAGGER_PATH}

  api-docs:
    path: ${API_DOCS_PATH}

#management:
#  endpoints:
#    web:
#      base-path: ${MANAGEMENT_PATH}
#      exposure:
#        include: health,info,beans,conditions,prometheus
#        exclude: threaddump, heapdump
#  endpoint:
#    prometheus:
#      access: unrestricted
#    health:
#      show-details: always
#  metrics:
#    distribution:
#      percentiles:
#        http.server.requests: 0.5, 0.95, 0.99  # P50, P95, P99 직접 계산
